name: Hashistack AMI's using Packer

on: [push, pull_request]

jobs:
  consul-ami-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Packer AMI Build
        uses: zmingxie/packer-ami-builder@v0.4
        with:
          packerVersion: '1.7.3'
          packerArgs: 'build consul-ami.pkr.hcl'
          workDir: '../../packer/consul/'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
